# repos:
# - repo: https://github.com/antonbabenko/pre-commit-terraform
#   rev: v1.88.4 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
#   hooks:
#     - id: terraform_fmt
#       args:
#         - --args=-recursive
#     - id: terraform_docs
#       args:
#         - --args=--config=.docs/.tfdocs-config.yml
#     # - id: terraform_validate


repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.17.0"
    hooks:
      - id: terraform-docs-go
        args: ["--config", ".docs/.tfdocs-config.yaml", "."]
